const Portfolio = [
    {
        id:1,
        image:"images/Lapeau_skincare.png",
        name:"La Peau Skincare",
        category: "Wordpress",
        description: " LA PEAU skincare is a 3-SKU skincare line (Night, Day and Eyes) from Switzerland.",
        link:"https://www.lapeauskincare.com/",
    },
    {
        id:2,
        image:"images/lrdg.png",
        name:"LRDG Online Portal",
        category: "Wordpress",
        description: "LRDG is an Online learning Platform.",
        link:"https://lrdgonline.com",
    },
    {
        id:3,
        image:"images/Miami.png",
        name:"Miami Exotic Car Rental",
        category: "Wordpress",
        description: "It is Car rental company provides the finest service and selection of exotic and luxury cars for rent in South Florida.",
        link:"https://miamiexoticcarrental.com/",
    },
    {
        id:4,
        image:"images/BigSkyDirect.png",
        name:"BigSky Direct",
        category: "Wordpress",
        description: "BigSky Direct is the leading HIGH-SPEED Internet Provider to homes and businesses.",
        link:"https://myportal.bigskynetworks.com/crm/login",
    },
    {
        id:5,
        image:"images/Copper_creek_kennel.png",
        name:"Copper Creek kennels",
        category: "Wordpress",
        description: "Copper Creek Kennels a is safe, clean, licensed and insured pet boarding facility.",
        link:"http://coppercreekkennels.com/"
    },
    {
        id:6,
        image:"images/Destination_canada.png",
        name:"Destination Canada",
        category: "Drupal",
        description: "Destination Canada helps to find the travel locations in Canada.",
        link:"https://travel.destinationcanada.com/",
    },
    {
        id:7,
        image:"images/Dilitrust_exec.png",
        name:"Dilitrust Exec",
        category: "Drupal",
        description: "Online Board Management system ",
        link:"https://exec-na.dilitrust.com/eng",
    },
    {
        id:8,
        image:"images/BlueMoonTalent.png",
        name:"Blue Moon Talent",
        category: "Codeigniter",
        description: "Provides brilliant entertainment solutions",
        link:"https://www.bluemoontalent.com/",
    },
    {
        id:9,
        image:"images/BlueMoonTalentAdmin.png",
        name:"Blue Moon Talent Admin Portal",
        category: "Codeigniter",
        description: "Handle and manages all the operation from Admin Portal",
        link:"http://cms.bluemoontalent.com/",
    },
    ,
    {
        id:10,
        image:"images/remediumfarm.png",
        name:"Remedium Farm",
        category: "Magento",
        description: "Handle and manages all the operation from Admin Portal",
        link:"https://www.remediumfarm.ro/",
    },
  /*   {
        id:11,
        image:"images/BlueMoonTalentAdmin.png",
        name:"Pola dot peacok",
        category: "Magento",
        description: "Online store of Home bedding, decor and furniture.",
        link:"http://cms.bluemoontalent.com/",
    }, */
    {
        id:12,
        image:"images/IPC.png",
        name:"Investment Planning Council",
        category: "ExpressionEngine",
        description: "IPC is an Investment Planning Council which provides finanicial solutions for life.",
        link:"https://ipc.opilink.com/g_myacct/login",
    } ,
    {
        id:13,
        image:"images/thia.png",
        name:"THIA travel Insurance Program",
        category: "ExpressionEngine",
        description: "TRIP is an in-depth, online curriculum about travel health insurance.",
        link:"https://thia.opilink.com/",
    },
    {
        id:14,
        image:"images/Blog-website.png",
        name:"Blog Website",
        category: "React",
        description: "Implemented User Sign Up, User login, User can add comments to the blogs and articles, Listed all the articles and usercan upvote the article.",
        link:"/",
    }, 
    {
        id:15,
        image:"images/netflix.png",
        name:"Top 5 Netflix series",
        category: "React",
        description: "List my top 5 Netflix series. This is my personal project where I learned basics of Node js and React JS and practiced to develop small list.",
        link:"https://boisterous-bonbon-f5ede9.netlify.app/",
       
    },
    {
        id:16,
        image:"images/Sunlife.png",
        name:"Sunlife Financial",
        category: "ExpressionEngine",
        description: "Contributed in development of new modules and developed product report and student report.",
        link:"https://sunlife.oliverslearning.com/",
    },
    {
        id:17,
        image:"images/opi.png",
        name:"Olivers Admin Portal",
        category: "ExpressionEngine",
        description: "Contributed in development of Admin Portal new modules like User-role-sites permisions, Generated reports, CIPR report etc.",
        link:"https://opidevservices.com/",
    }

];

export default Portfolio;
